Free 72 scrape library
csesoc/freerooms pull request #405
Opened 2023-09-24 11:36 UTC by chrozure

Created a scraper to scrape room bookings for library rooms. Currently only does main library rooms but it can also find law library rooms with a quick change.

2023-09-24 13:35 UTC, francojreyes requested changes

2023-09-24 13:35 UTC, francojreyes commented on v2/backend/src/libraryScraper.js
What is this file? lol

2023-09-24 13:35 UTC, francojreyes commented on v2/backend/src/libraryScraper.ts
> +import { setPriority } from 'os';
what is this import? doesn't look like its being used

2023-09-24 13:35 UTC, francojreyes commented on v2/backend/src/libraryScraper.ts
> +                bookingType: 'Study Room',
the other booking types are all in caps (e.g. CLASS, SOCIETY) so to be consistent, this should match - maybe STUDY or LIBRARY?

2023-09-24 13:35 UTC, francojreyes commented on v2/backend/src/libraryScraper.ts
> +    console.log(allRoomBookings);
remove lol

2023-09-24 13:35 UTC, francojreyes commented on v2/backend/src/libraryScraper.ts
> +        usage: "Study Room",
these are also all caps, so again maybe STUDY or LIB

2023-09-24 13:35 UTC, francojreyes commented on v2/backend/src/libraryScraper.ts
> +                    end: new Date(slot.end),
might need to double check the timezones on these

2023-09-24 13:35 UTC, francojreyes commented on v2/backend/src/libraryScraper.ts
> +        id: roomId,
these are just the numeric item ids from the site right? but it should match the format of other room ids which is {buildingId}-{roomNumber} (e.g. K-J17-101). you can probably just prepend the building ids, main lib is K-F21 and law bldg is K-E8. so like K-F21-46481 or smth is fine.

2023-09-24 13:35 UTC, francojreyes commented on v2/backend/src/libraryScraper.ts
> +        school: "Library"
the school field is supposed to indicate which school you need to book through - since these can be booked by anyone just make them a space like the CATS rooms (`" "`, NOT empty string)

2023-09-29 06:46 UTC, francojreyes commented
Also !!! we don't want date hardcoded. try find out what the range of usable dates is, and dynamically calculate this. if possible, scraping the whole year would be cool (which is what nss scraper does).

2023-09-29 06:50 UTC, francojreyes commented on v2/backend/src/libraryScraper.ts
> +                    end: new Date(slot.end),
might want to pass it through this function https://github.com/csesoc/nss-scraper/blob/main/src/toSydneyTime.ts

2023-10-04 01:39 UTC, chrozure commented on v2/backend/src/libraryScraper.js
gone now

2023-10-04 01:45 UTC, chrozure commented on v2/backend/src/libraryScraper.ts
> +import { setPriority } from 'os';
true!

2023-10-04 01:45 UTC, chrozure commented on v2/backend/src/libraryScraper.ts
> +                bookingType: 'Study Room',
done

2023-10-04 02:07 UTC, chrozure commented on v2/backend/src/libraryScraper.ts
> +                    end: new Date(slot.end),
is there an easy way to get that function other than copy pasting it?

2023-10-04 02:09 UTC, francojreyes commented on v2/backend/src/libraryScraper.ts
> +                    end: new Date(slot.end),
No lol. I also don't know if it's necessary/works for this scraper. I haven't taken a look at the date formats in the data.

2023-10-04 02:36 UTC, chrozure commented on v2/backend/src/libraryScraper.ts
> +import { setPriority } from 'os';
the fs is used for some debugging

2023-10-04 02:37 UTC, chrozure commented on v2/backend/src/libraryScraper.ts
> +    console.log(allRoomBookings);
do we want two functions - one for just the roomdata and one for the roombookings?

2023-10-04 02:41 UTC, francojreyes commented on v2/backend/src/libraryScraper.ts
> +    console.log(allRoomBookings);
I think it's fine as is

2023-10-13 04:59 UTC, closed without merging