Frontend
csesoc/Freerooms pull request #8
Opened 2020-09-09 10:30 UTC by natLF3RD

Frontend static design merge into master.
Unintegrated with backend.

Contains the following page designs:
- Building list page
- Room list page
- Room occupancy page

2020-09-09 10:40 UTC, Choco3-3 requested changes
Please refer to comments for suggestions and request for reasoning on specific changes.

2020-09-09 10:40 UTC, Choco3-3 commented on frontend/.browserslistrc
> +not dead
What is the point of this file?

2020-09-09 10:40 UTC, Choco3-3 commented on frontend/.gitignore
> +*.sw?
Why is there a gitignore inside a folder when there is already a gitignore on the top level?

2020-09-09 10:40 UTC, Choco3-3 commented on frontend/src/models/bindingModel.ts
> +        for(let room of json.BookedTimeSlots) {
The `for` loop style for this project includes a space after the `for` keyword

2020-09-10 06:57 UTC, natLF3RD commented on frontend/.browserslistrc
> +not dead
Its  a file generated by the Vue cli. Used to indicate browser compatibility it seems.

2020-09-10 06:58 UTC, natLF3RD commented on frontend/src/models/bindingModel.ts
> +        for(let room of json.BookedTimeSlots) {
fixed

2020-09-10 08:36 UTC, natLF3RD commented on frontend/.gitignore
> +*.sw?
I've merged it's contents into root now.

2020-09-10 09:15 UTC, Choco3-3 approved these changes
LGTM!

2020-09-10 09:15 UTC, merged